# Generated by Django 4.1.3 on 2025-01-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="ingredient", name="description",),
        migrations.RemoveField(model_name="ingredient", name="title",),
    ]
