# Generated by Django 4.1.3 on 2025-01-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_course"),
        ("ingredients", "0002_remove_ingredient_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="related_recipe",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: If this ingredient is a recipe, link the recipe here.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_as_ingredient",
                to="recipes.recipe",
            ),
        ),
    ]
