# Generated by Django 4.1.3 on 2025-01-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_ingredient_related_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionaltable",
            name="servings",
            field=models.FloatField(
                blank=True, help_text="Servings per container", null=True
            ),
        ),
    ]
