FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN set -e; \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        netcat-traditional \
        gettext \
        httpie && \
    pip install --upgrade pip && \
    pip install flask

RUN mkdir /code
WORKDIR /code

# Copy server.py to /code in the container
COPY ./server.py .

# Debug: Verify that the file is correctly copied
RUN ls -l /code

ENTRYPOINT ["python", "./server.py"]
