# Generated by Django 4.1.3 on 2025-01-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.tag",
            ),
        ),
    ]
