# Generated by Django 4.1.3 on 2025-01-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="equipment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
