# Generated by Django 4.1.3 on 2025-01-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0003_tag_recipe_author_recipe_cook_time_recipe_cool_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.tag",
            ),
        ),
    ]
