# Generated by Django 4.1.3 on 2025-01-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_equipment_recipe_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_card",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipes_images/card/"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="number_of_ratings",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="The number of user ratings for this recipe.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipes_images/feature/"
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
