# Generated by Django 4.1.3 on 2025-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_image_card_recipe_number_of_ratings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="groupName",
            field=models.TextField(blank=True, null=True),
        ),
    ]
