# Generated by Django 4.1.3 on 2025-01-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_recipeingredient_groupname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="groupName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="notes",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
