# Generated by Django 4.1.3 on 2025-01-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_recipeingredient_groupname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
