# Generated by Django 4.1.3 on 2025-01-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_course_cuisine_remove_recipe_course_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course", options={"verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="cuisine", options={"verbose_name_plural": "Cuisines"},
        ),
        migrations.AddField(
            model_name="recipe",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipes.course"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cuisines",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipes.cuisine"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipes.tag"
            ),
        ),
    ]
